//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActAboutRepair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActAboutRepair()
        {
            this.Workshop = new HashSet<Workshop>();
        }
    
        public int Id_ActAboutRepair { get; set; }
        public int Id_User { get; set; }
        public Nullable<int> Id_Phone { get; set; }
        public Nullable<int> Id_Type_Malfuction { get; set; }
        public string Description_ActAboutRepair { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Id_ConsumableMaterial { get; set; }
    
        public virtual ConsumableMaterial ConsumableMaterial { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual Type_Malfunction Type_Malfunction { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshop { get; set; }
    }
}
