//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id_Request { get; set; }
        public string Name_Request { get; set; }
        public Nullable<int> Id_ShopClient { get; set; }
    
        public virtual ShopClient ShopClient { get; set; }
    }
}
