//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id_Shop { get; set; }
        public string Name_Shop { get; set; }
        public Nullable<int> Id_Phone { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual Phone Phone { get; set; }
        public virtual User User { get; set; }
    }
}
