//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int Id_Storage { get; set; }
        public Nullable<int> Id_ConsumableMaterial { get; set; }
        public Nullable<int> Id_Money_Fasilities { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual ConsumableMaterial ConsumableMaterial { get; set; }
        public virtual Money_Fasilities Money_Fasilities { get; set; }
    }
}
