//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelephoneShopDBEntities1 : DbContext
    {
        public TelephoneShopDBEntities1()
            : base("name=TelephoneShopDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActAboutRepair> ActAboutRepair { get; set; }
        public virtual DbSet<ConsumableMaterial> ConsumableMaterial { get; set; }
        public virtual DbSet<Money_Fasilities> Money_Fasilities { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopClient> ShopClient { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Malfunction> Type_Malfunction { get; set; }
        public virtual DbSet<Type_Phone> Type_Phone { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
