//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2022_Gizetdinov421.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public int Id_Workshop { get; set; }
        public Nullable<int> Id_ActAboutRepair { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> WokersAmount { get; set; }
    
        public virtual ActAboutRepair ActAboutRepair { get; set; }
        public virtual User User { get; set; }
    }
}
